### ISSUE TITLE
Crashes a few seconds after loading in browser

### ISSUE THREAD

**Issue by scottdotjs** [jsonhero-io/jsonhero-web#25]
How to replicate:
- Clone repo and `npm install`
- `npm start`
- Browse to `http://localhost:8787`
- Wait for about 5 seconds

This error appears in the browser:
```
Error: Unexpected Server Error
    at handleDataRequest (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/server-runtime/esm/server.js:163:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at requestHandler (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/server-runtime/esm/server.js:41:20)
    at handleEvent (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/cloudflare-workers/esm/worker.js:98:18)
    at EventTarget.[kDispatchFetch] (/Users/scott/Tools/jsonhero-web/node_modules/@miniflare/core/src/standards/event.ts:359:13)
    at Server.<anonymous> (/Users/scott/Tools/jsonhero-web/node_modules/@miniflare/http-server/src/index.ts:168:20)
```

In the console:

```
[1] GET /build/routes/actions/getPreview.$url-JE4JRBGI.js 200 OK (6.18ms)
[1] ReferenceError: PEEKALINK_API_KEY is not defined
[1]     at getPeekalink (/Users/scott/Tools/jsonhero-web/app/services/uriPreview.server.ts:17:3)
[1]     at getUriPreview (/Users/scott/Tools/jsonhero-web/app/services/uriPreview.server.ts:71:33)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at loader2 (/Users/scott/Tools/jsonhero-web/build/route:/Users/scott/Tools/jsonhero-web/app/routes/actions/getPreview.$url.ts:10:18)
[1]     at callRouteLoader (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/server-runtime/esm/data.js:69:14)
[1]     at handleDataRequest (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/server-runtime/esm/server.js:125:18)
[1]     at requestHandler (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/server-runtime/esm/server.js:41:20)
[1]     at handleEvent (/Users/scott/Tools/jsonhero-web/node_modules/@remix-run/cloudflare-workers/esm/worker.js:98:18)
[1]     at EventTarget.[kDispatchFetch] (/Users/scott/Tools/jsonhero-web/node_modules/@miniflare/core/src/standards/event.ts:359:13)
[1]     at Server.<anonymous> (/Users/scott/Tools/jsonhero-web/node_modules/@miniflare/http-server/src/index.ts:168:20)
[1] GET /actions/getPreview/https%3A%2F%2Fwww.theonion.com%2F?_data=routes%2Factions%2FgetPreview.%24url 500 Internal Server Error (557.21ms)
```

(Why is it trying to load a page on theonion.com?)

My environment:
macOS 12.3.1, MacBook Air (M1, 2020)
Node v16.13.2
Firefox 100.0b9

**Comment by ericallam** [comment]
Just fixed this issue in #a40eeaae678a 👍
