### ISSUE TITLE
[Chore] Investigate developing with node.js 18

### ISSUE THREAD

**Issue by ericallam** [jsonhero-io/jsonhero-web#57]
It looks like this error reported to us could be caused by node.js 18:

```
[1] [mf:wrn] Cache operations will have no impact if you deploy to a workers.dev subdomain!
[1] TypeError: Value of "this" must be of type Crypto
[1]     at new NodeError (node:internal/errors:372:5)
[1]     at getRandomValues (node:internal/crypto/webcrypto:732:11)
[1]     at Proxy.<anonymous> (/Users/.../Desktop/JS/jsonhero-web/node_modules/@miniflare/core/src/standards/helpers.ts:35:16)
[1]     at /Users/.../Desktop/JS/jsonhero-web/app/jsonDoc.server.ts:115:14
[1]     at /Users/.../Desktop/JS/jsonhero-web/node_modules/nanoid/index.js:26:19
[1]     at createId (/Users/.../Desktop/JS/jsonhero-web/app/jsonDoc.server.ts:119:10)
[1]     at createFromRawJson (/Users/.../Desktop/JS/jsonhero-web/app/jsonDoc.server.ts:67:17)
[1]     at createFromUrlOrRawJson (/Users/.../Desktop/JS/jsonhero-web/app/jsonDoc.server.ts:36:12)
[1]     at action2 (/Users/.../Desktop/JS/jsonhero-web/build/route:/Users/.../Desktop/JS/jsonhero-web/app/routes/actions/createFromUrl.ts:26:21)
[1]     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
[1]   code: 'ERR_INVALID_THIS'
[1] }
[1] POST /actions/createFromUrl?_data=routes%2Factions%2FcreateFromUrl 500 Internal Server Error (1157.81ms)
```

**Comment by 123om123** [comment]
@ericallam Maybe we should close this issue since you fixed it with the miniflare update?
